/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-03-26 06:17:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class maincontent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("    \r\n");

    HttpSession loginsession = request.getSession();

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Title</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("	body {\r\n");
      out.write("		text-align : center;\r\n");
      out.write("		background-repeat: no-repeat;\r\n");
      out.write("   		background-size: cover;\r\n");
      out.write("	}\r\n");
      out.write("	.maintitle img {\r\n");
      out.write("	 width: 700px;\r\n");
      out.write(" 	 height: 200px; \r\n");
      out.write("	}\r\n");
      out.write("	table {\r\n");
      out.write("		margin : 0 auto;\r\n");
      out.write("	}\r\n");
      out.write("	body {\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	.table1 {\r\n");
      out.write("	 	display: flex;\r\n");
      out.write("	  	justify-content: center;\r\n");
      out.write("	}\r\n");
      out.write("	.table1 table {\r\n");
      out.write("	 	border-collapse: collapse;\r\n");
      out.write("	}\r\n");
      out.write("	.text1 h1 {\r\n");
      out.write("		margin: 0;\r\n");
      out.write("	}\r\n");
      out.write(" 	.table1 td {\r\n");
      out.write("		padding: 40px;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		font-family: Arial, sans-serif;\r\n");
      out.write("	}\r\n");
      out.write("	.table1 img {\r\n");
      out.write("		width: 150px;\r\n");
      out.write("		height: 150px;\r\n");
      out.write("	}\r\n");
      out.write("	.table1 p{\r\n");
      out.write("		color : #78A9ED	;	\r\n");
      out.write("		font-weight : bold;\r\n");
      out.write("		font-size : 20px;\r\n");
      out.write("	}\r\n");
      out.write("	.table1 pre{\r\n");
      out.write("		font-weight : bold;\r\n");
      out.write("		color : gray;\r\n");
      out.write("		font-family: Arial, sans-serif;\r\n");
      out.write("	}\r\n");
      out.write("	.table1 a {\r\n");
      out.write("	  	text-decoration: none;\r\n");
      out.write("	}\r\n");
      out.write("	.table1 img:hover{\r\n");
      out.write("  		 filter: grayscale(50%); /* 이미지 회색 톤 효과 추가 */\r\n");
      out.write(" 		 transform: scale(0.95); /* 이미지 크기 약간 축소 */\r\n");
      out.write(" 	}\r\n");
      out.write("	.popular {\r\n");
      out.write("	  	display: flex;\r\n");
      out.write("	  	justify-content: center;\r\n");
      out.write("	  	align-items: center;\r\n");
      out.write("	}\r\n");
      out.write("	.flex-container {\r\n");
      out.write("		display: flex;\r\n");
      out.write("		flex-wrap: wrap;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.flex-container > div {\r\n");
      out.write("		width: 33.33%;\r\n");
      out.write("		height: 200px;\r\n");
      out.write("		background-size: cover;\r\n");
      out.write("		background-repeat: no-repeat;\r\n");
      out.write("		background-position: center center;\r\n");
      out.write("		position: relative;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.flex-container > div > h3 {\r\n");
      out.write("		position: absolute;\r\n");
      out.write("		bottom: 0;\r\n");
      out.write("		left: 0;\r\n");
      out.write("		right: 0;\r\n");
      out.write("		padding: 10px;\r\n");
      out.write("		background-color: rgba(0, 0, 0, 0.5);\r\n");
      out.write("		color: #fff;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.flex-container > div:nth-child(odd) {\r\n");
      out.write("		height: 400px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.flex-container > div:nth-child(odd) > h3 {\r\n");
      out.write("		top: 0;\r\n");
      out.write("		bottom: initial;\r\n");
      out.write("	}\r\n");
      out.write("	.flex-container div:hover {\r\n");
      out.write(" 		 transform: scale(1.1);\r\n");
      out.write("	}\r\n");
      out.write("	.popular {\r\n");
      out.write("  		display: flex;\r\n");
      out.write("  		justify-content: center;\r\n");
      out.write("  		align-items: center;\r\n");
      out.write("	}\r\n");
      out.write("	.popular img{\r\n");
      out.write("		 width: 600px;\r\n");
      out.write("	 	 height: 200px; \r\n");
      out.write("	}\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body> \r\n");
      out.write("<br><br>\r\n");
      out.write("<div class = \"maintitle\">\r\n");
      out.write("	<img src=\"./pageimage/mainimage/tralogo.png\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class = \"table1\"> \r\n");
      out.write("	<table>\r\n");
      out.write("	<tr> \r\n");
      out.write("	\r\n");
      out.write("	<td>\r\n");
      out.write("	<a href=\"trip.do\">\r\n");
      out.write("		<img src = \"./pageimage/mainimage/mainlocal.png\">\r\n");
      out.write("		<p> 지역별여행</p>\r\n");
      out.write("		<pre>우리나라, 어디까지 가봤니?\r\n");
      out.write("아름다운 여행지를\r\n");
      out.write("트래벌룬에서 만나보세요.</pre>\r\n");
      out.write("	</a>\r\n");
      out.write("	</td>\r\n");
      out.write("	\r\n");
      out.write("	<td>\r\n");
      out.write("	<a href=\"hotel.do\">\r\n");
      out.write("	<img src = \"pageimage/mainimage/mainhotels.png\">\r\n");
      out.write("		<p>숙소추천</p>\r\n");
      out.write("	<pre>감성숙소부터 안락한 호텔까지!\r\n");
      out.write("여행 중 지친 몸과 마음,\r\n");
      out.write("편안한 숙소에서 쉬어가세요.</pre>\r\n");
      out.write("	</a>\r\n");
      out.write("	</td>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<td>\r\n");
      out.write("	<a href=\"review.do\"> \r\n");
      out.write("	<img src = \"./pageimage/mainimage/mainreview.png\">\r\n");
      out.write("		<p>여행리뷰</p>\r\n");
      out.write("	<pre>나만의 국내 추천 코스를\r\n");
      out.write("많은 사람들에게 공유해주세요!\r\n");
      out.write("#여행코스 #여행추천 #리뷰</pre>\r\n");
      out.write("	</a>\r\n");
      out.write("	</td>\r\n");
      out.write("	 \r\n");
      out.write("	<td>\r\n");
      out.write("	<a href=\"community.do\"?>\r\n");
      out.write("	<img src = \"./pageimage/mainimage/maincommunity.png\">\r\n");
      out.write("		<p>커뮤니티</p>\r\n");
      out.write("	<pre>다양한 정보를 공유할 수 있어요.\r\n");
      out.write("여행과 관련된 나의 생각을\r\n");
      out.write("이곳에서 펼쳐볼까요?</pre>\r\n");
      out.write("	</a>\r\n");
      out.write("	</td>\r\n");
      out.write("\r\n");
      out.write("	</tr>\r\n");
      out.write("	 \r\n");
      out.write("	</table>\r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write(" \r\n");
      out.write("<div style=\"border-top: 1px solid #dcdcdc; width: 700px; margin: 0 auto;\"></div> 	<!-- 회색 구분선 -->\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("<div class=\"popular\"> \r\n");
      out.write("	<img src = \"./pageimage/mainimage/recent.png\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("<div class=\"flex-container\">\r\n");
      out.write("	<div style=\"background-image: url('./pageimage/tripImage/trip-seoul.png');\" onclick=\"location.href='./tripcity.do?name=seoul';\">\r\n");
      out.write("		<h3>SEOUL</h3>\r\n");
      out.write("	</div>	\r\n");
      out.write("	<div style=\"background-image: url();\">		\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div style=\"background-image: url('./pageimage/tripImage/trip-jeju.png');\" onclick=\"location.href='./tripcity.do?name=jeju';\">\r\n");
      out.write("		<h3>JEJU</h3>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div style=\"background-image: url();\">\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div style=\"background-image: url('./pageimage/tripImage/trip-chungcheong.png');\" onclick=\"location.href='./tripcity.do?name=chungcheong';\">\r\n");
      out.write("		<h3>CHUNGCHEONG</h3>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div style=\"background-image: url();\">\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div style=\"background-image: url('./pageimage/tripImage/trip-gangwon.png');\" onclick=\"location.href='./tripcity.do?name=gangwon';\">\r\n");
      out.write("		<h3>GANGWON</h3>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div style=\"background-image: url();\">\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div style=\"background-image: url('./pageimage/tripImage/trip-gyeongsang.png');\" onclick=\"location.href='./tripcity.do?name=gyeongsang';\">\r\n");
      out.write("		<h3>GYEONGSANG</h3>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div style=\"background-image: url();\">\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div style=\"background-image: url('./pageimage/mainimage/trip_jeolla.png');\" onclick=\"location.href='./tripcity.do?name=jeolla';\">\r\n");
      out.write("		<h3>JEOLLA</h3>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div style=\"background-image: url();\">\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("</div>\r\n");
      out.write("	<br><br>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<!-- <p style=\"line-height: 30em;\">&nbsp;</p>  --> <!-- 줄간격 -->\r\n");
      out.write("</html>\r\n");
      out.write("    \r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
