/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-03-20 06:53:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.loginScreen;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/tiles-jsp-3.0.7.jar", Long.valueOf(1676953121996L));
    _jspx_dependants.put("jar:file:/C:/Users/PC/Desktop/_team_project/Traballoon_bdy_v4.0/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Tiles-Traballoon/WEB-INF/lib/tiles-jsp-3.0.7.jar!/META-INF/tld/tiles-jsp.tld", Long.valueOf(1470892568000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype HTML>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>로그인</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/login.css\">\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/51db22a717.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- BootStrap -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("    	 .toggle.ios, .toggle-on.ios, .toggle-off.ios { border-radius: 20px; }\r\n");
      out.write("  		.toggle.ios .toggle-handle { border-radius: 20px; }\r\n");
      out.write("  		\r\n");
      out.write("        header h1 {\r\n");
      out.write("            font-size: 50px;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        body{\r\n");
      out.write("			/* background:var(--body-background-color); */\r\n");
      out.write("			/* 배경 꽉차게 */\r\n");
      out.write("			background: linear-gradient(rgba(0, 0, 0, 0.2),rgba(0, 0, 0, 0.2)),\r\n");
      out.write("							url('./pageimage/mainImage/image01.jpg')\r\n");
      out.write("							no-repeat center fixed;\r\n");
      out.write("			-webkit-background-size: cover;\r\n");
      out.write("			-moz-background-size: cover;\r\n");
      out.write("			-o-background-size: cover;\r\n");
      out.write("			background-size: cover;\r\n");
      out.write("		}\r\n");
      out.write("		.form-check-label {\r\n");
      out.write("			width: 465px;\r\n");
      out.write("			height: 52px;\r\n");
      out.write("			font-size: 15px;\r\n");
      out.write("			color: white;\r\n");
      out.write("			align-items: center;\r\n");
      out.write("			justify-content: flex-start;\r\n");
      out.write("/* 	 		border-bottom: solid 1px var(--border-gray-color); */\r\n");
      out.write("		}\r\n");
      out.write("		a {\r\n");
      out.write("			text-decoration: none;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		a:hover {\r\n");
      out.write("			text-decoration: underline;\r\n");
      out.write("			color:#666;\r\n");
      out.write("        }\r\n");
      out.write("  \r\n");
      out.write("        \r\n");
      out.write("        .login-button-wrap:hover {\r\n");
      out.write("        	--green-color:#666;\r\n");
      out.write("			--green-border-color: #666;\r\n");
      out.write("        }\r\n");
      out.write("		\r\n");
      out.write("        .blog-header-logo {\r\n");
      out.write("            font-family: \"Playfair Display\", Georgia, \"Times New Roman\", serif;\r\n");
      out.write("            font-size: 3.5rem;\r\n");
      out.write("            color: white;\r\n");
      out.write("            text-shadow: 0 2px 20px rgba(0,0,0,0);\r\n");
      out.write("        }b \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        .main-container {\r\n");
      out.write("        	margin-top:20%;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("         /* 화면 넓어졌을때 */\r\n");
      out.write("        @media (min-width: 1000px) {\r\n");
      out.write("        	.main-container {\r\n");
      out.write("        		margin-top: none;\r\n");
      out.write("        	}\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"main-container\">\r\n");
      out.write("    <header class=\"blog-header py-3\">\r\n");
      out.write("         <div class=\"col-4 text-center\">\r\n");
      out.write("                <a class=\"blog-header-logo\" href=\"main.do\">Traballoon</a>\r\n");
      out.write("         </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <form action=\"loginAf.do\" method=\"post\" class=\"login-input-section-wrap\">\r\n");
      out.write("        <div class=\"login-input-wrap\">\r\n");
      out.write("            <input id=\"id\" name=\"id\" placeholder=\"Username\" type=\"text\"></input>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"login-input-wrap password-wrap\">\r\n");
      out.write("            <input id=\"pwd\" name=\"pwd\" placeholder=\"Password\" type=\"password\"></input>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"login-button-wrap\">\r\n");
      out.write("            <button type=\"submit\">Sign in</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br>\r\n");
      out.write("        <div class=\"form-check form-switch\" style=\"padding-left: 20%;\">\r\n");
      out.write("            <input class=\"form-check-input\" type=\"checkbox\" role=\"switch\" value=\"\" class=\"chk_save_id\" id=\"flexSwitchCheckDefault\"></input>\r\n");
      out.write("            <label class=\"form-check-label\" for=\"flexSwitchCheckDefault\">remember id, password</label>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("    <section class=\"Easy-sgin-in-wrap\">\r\n");
      out.write("        <a href=\"\" class=\"forget-msg\">Forgot your Username or Password?</a>\r\n");
      out.write("        <a href=\"#\" onclick=\"account()\" class=\"forget-msg\">Sign up</a>\r\n");
      out.write("    </section>\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"copyright-wrap\">\r\n");
      out.write("            <span>Thank you for visiting Multicampus Team Four's website!</span>\r\n");
      out.write("        	<br>\r\n");
      out.write("        	<p style=\"font-size: 12px;\">Designed and developed by | 권하나, 김동민, 김영권, 백다연, 심재훈 | © 2023 All Rights Reserved</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    function account() {\r\n");
      out.write("        location.href = \"regi.do\";\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    let user_id = $.cookie(\"user_id\");\r\n");
      out.write("\r\n");
      out.write("    if (user_id != null) {	// 저장한 id가 있음\r\n");
      out.write("        $(\"#id\").val(user_id);\r\n");
      out.write("        $(\".chk_save_id\").prop(\"checked\", true);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    $(\".chk_save_id\").click(function () {\r\n");
      out.write("\r\n");
      out.write("        if ($(\".chk_save_id\").is(\":checked\") == true) {\r\n");
      out.write("\r\n");
      out.write("            if ($(\"#id\").val().trim() == \"\") {\r\n");
      out.write("                alert('id를 입력해 주십시오');\r\n");
      out.write("                $(\".chk_save_id\").prop(\"checked\", false);\r\n");
      out.write("            } else {\r\n");
      out.write("                // cookie를 저장\r\n");
      out.write("                $.cookie(\"user_id\", $(\"#id\").val().trim(), {expires: 7, path: './'});\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        } else {\r\n");
      out.write("            $.removeCookie(\"user_id\", {path: './'});\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
