/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-03-26 06:29:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.tripScreen;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import mul.cam.a.dto.MemberDto;

public final class tripmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("mul.cam.a.dto.MemberDto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>Title</title>\n");
      out.write("    <style>\n");
      out.write("        p {\n");
      out.write("            font-size: 12px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        h3 {\n");
      out.write("            font-size: 15px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card-body {\n");
      out.write("            height: 145px; /* 원하는 높이값 */\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .citycard {\n");
      out.write("            color: #333; /* 원하는 색상으로 변경 */\n");
      out.write("            text-decoration: none; /* 텍스트 밑줄 제거 */\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .citycard:hover {\n");
      out.write("            text-decoration: none; /* 마우스 오버시 텍스트 밑줄 제거 */\n");
      out.write("            color: #333;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .image-container {\n");
      out.write("            position: relative;\n");
      out.write("            display: inline-block;\n");
      out.write("            padding: 15px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card-img-top {\n");
      out.write("            max-width: 100%;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .image-text h2 {\n");
      out.write("            font-size: 24px;\n");
      out.write("            color: #fff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("    </style>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"container\">\n");
      out.write("\n");
      out.write("    <br>\n");
      out.write("    <div class=\"row\">\n");
      out.write("        ");
      out.write("\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("            <div class=\"card\">\n");
      out.write("                <a class=\"citycard\" href=\"tripcity.do?name=seoul\">\n");
      out.write("                    <div class=\"image-container\" style=\"position: relative;\">\n");
      out.write("                        <img class=\"card-img-top\" src=\"pageimage/tripImage/trip-seoul.png\" alt=\"Card image cap\">\n");
      out.write("                        <span style=\"position: absolute; top: 30px; left: 30px; color: white; font-weight: bold; font-size: 30px\">서울</span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"card-body\">\n");
      out.write("                        <h3 class=\"card-title\">서울</h3>\n");
      out.write("                        <p class=\"card-text\">역사와 현대의 만남이 있는 도시, 한국의 중심지이자 대표적인 관광도시입니다.</p>\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        ");
      out.write("\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("            <div class=\"card\">\n");
      out.write("                <a class=\"citycard\" href=\"tripcity.do?name=gyeonggi\">\n");
      out.write("                    <div class=\"image-container\" style=\"position: relative;\">\n");
      out.write("                        <img class=\"card-img-top\" src=\"pageimage/tripImage/trip-gyeonggi.png\" alt=\"Card image cap\">\n");
      out.write("                        <span style=\"position: absolute; top: 30px; left: 30px; color: white; font-weight: bold; font-size: 30px\">경기</span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"card-body\">\n");
      out.write("                        <h3 class=\"card-title\">경기</h3>\n");
      out.write("                        <p class=\"card-text\">관광과 쇼핑의 메카, 수도권 최대의 국제도시인 인천과 경기도 일대를 아우르며 많은 인파를 유치합니다.</p>\n");
      out.write("                    </div>\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        ");
      out.write("\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("            <div class=\"card\">\n");
      out.write("                <a class=\"citycard\" href=\"tripcity.do?name=gangwon\">\n");
      out.write("                    <div class=\"image-container\" style=\"position: relative;\">\n");
      out.write("                        <img class=\"card-img-top\" src=\"pageimage/tripImage/trip-gangwon.png\" alt=\"Card image cap\">\n");
      out.write("                        <span style=\"position: absolute; top: 30px; left: 30px; color: white; font-weight: bold; font-size: 30px\">강원</span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"card-body\">\n");
      out.write("                        <h3 class=\"card-title\">강원</h3>\n");
      out.write("                        <p class=\"card-text\">청정한 자연과 풍부한 문화 유산, 세계적인 스키 리조트와 천혜의 자연 경관이 있는 도시입니다.</p>\n");
      out.write("                    </div>\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"row\">\n");
      out.write("        ");
      out.write("\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("            <div class=\"card\">\n");
      out.write("                <a class=\"citycard\" href=\"tripcity.do?name=chungcheong\">\n");
      out.write("                    <div class=\"image-container\" style=\"position: relative;\">\n");
      out.write("                        <img class=\"card-img-top\" src=\"pageimage/tripImage/trip-chungcheong.png\" alt=\"Card image cap\">\n");
      out.write("                        <span style=\"position: absolute; top: 30px; left: 30px; color: white; font-weight: bold; font-size: 30px\">충청</span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"card-body\">\n");
      out.write("                        <h3 class=\"card-title\">충청</h3>\n");
      out.write("                        <p class=\"card-text\">자연과 역사가 공존하는 고즈넉한 도시, 대한민국의 중심부에 위치하며 국내외 여행객들의 사랑을 받습니다.</p>\n");
      out.write("                    </div>\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        ");
      out.write("\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("            <div class=\"card\">\n");
      out.write("                <a class=\"citycard\" href=\"tripcity.do?name=jeolla\">\n");
      out.write("                    <div class=\"image-container\" style=\"position: relative;\">\n");
      out.write("                        <img class=\"card-img-top\" src=\"pageimage/tripImage/trip-jeolla.jpg\" alt=\"Card image cap\">\n");
      out.write("                        <span style=\"position: absolute; top: 30px; left: 30px; color: white; font-weight: bold; font-size: 30px\">전라</span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"card-body\">\n");
      out.write("                        <h3 class=\"card-title\">전라</h3>\n");
      out.write("                        <p class=\"card-text\">역사와 문화가 깊게 새겨진 고요한 도시, 세계적으로 유명한 순천만습지를 비롯해 많은 자연과 문화유산을 보유하고 있습니다.</p>\n");
      out.write("                    </div>\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        ");
      out.write("\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("            <div class=\"card\">\n");
      out.write("                <a class=\"citycard\" href=\"tripcity.do?name=gyeongsang\">\n");
      out.write("                    <div class=\"image-container\" style=\"position: relative;\">\n");
      out.write("                        <img class=\"card-img-top\" src=\"pageimage/tripImage/trip-gyeongsang.png\" alt=\"Card image cap\">\n");
      out.write("                        <span style=\"position: absolute; top: 30px; left: 30px; color: white; font-weight: bold; font-size: 30px\">경상</span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"card-body\">\n");
      out.write("                        <h3 class=\"card-title\">경상</h3>\n");
      out.write("                        <p class=\"card-text\">바다와 산, 역사와 문화의 향연, 부산과 울산, 대구와 경주, 그리고 현대화와 전통이 공존하는 곳입니다.</p>\n");
      out.write("                    </div>\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"row\">\n");
      out.write("        ");
      out.write("\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("            <div class=\"card\">\n");
      out.write("                <a class=\"citycard\" href=\"tripcity.do?name=jeju\">\n");
      out.write("                    <div class=\"image-container\" style=\"position: relative;\">\n");
      out.write("                        <img class=\"card-img-top\" src=\"pageimage/tripImage/trip-jeju.png\" alt=\"Card image cap\">\n");
      out.write("                        <span style=\"position: absolute; top: 30px; left: 30px; color: white; font-weight: bold; font-size: 30px\">제주</span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"card-body\">\n");
      out.write("                        <h3 class=\"card-title\">제주</h3>\n");
      out.write("                        <p class=\"card-text\">한국의 남쪽 끝, 온갖 자연과 문화를 만날 수 있는 최고의 여행지이자 세계 자연유산입니다.</p>\n");
      out.write("                    </div>\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        ");
      out.write("\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("            <div class=\"card\">\n");
      out.write("                <a class=\"citycard\" href=\"tripcity.do?name=incheon\">\n");
      out.write("                    <div class=\"image-container\" style=\"position: relative;\">\n");
      out.write("                        <img class=\"card-img-top\" src=\"pageimage/tripImage/trip-incheon.png\" alt=\"Card image cap\">\n");
      out.write("                        <span style=\"position: absolute; top: 30px; left: 30px; color: white; font-weight: bold; font-size: 30px\">인천</span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"card-body\">\n");
      out.write("                        <h3 class=\"card-title\">인천</h3>\n");
      out.write("                        <p class=\"card-text\">미래도시, 인천공항을 비롯한 유네스코 인류문화유산인 중구청사, 자유공원 등 다양한 관광지를 보유하고 있습니다.</p>\n");
      out.write("                    </div>\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<br>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
