/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-03-26 06:17:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.reviewScreen;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import mul.cam.a.dto.MemberDto;
import mul.cam.a.dto.ReviewComment;
import mul.cam.a.dto.ReviewDto;
import java.util.List;

public final class reviewdetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("mul.cam.a.dto.ReviewComment");
    _jspx_imports_classes.add("mul.cam.a.dto.MemberDto");
    _jspx_imports_classes.add("mul.cam.a.dto.ReviewDto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <title>SemiProject</title>\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\">\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.slim.min.js\"></script>\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");

    ReviewDto dto = (ReviewDto) request.getAttribute("dto");
    
	
	Object loginObj = session.getAttribute("login");	//dto에 안담겨있을 수도 있으므로
	MemberDto login = new MemberDto(); //초기화해주기
	
	boolean isS = false;
	if(loginObj == null){
		
      out.write("\n");
      out.write("		<script>\n");
      out.write("			alert('로그인 해 주십시오');\n");
      out.write("			location.href = \"login.do\";\n");
      out.write("		</script>\n");
      out.write("		");

		} else {
			login = (MemberDto)session.getAttribute("login");
			isS = true;
		}
		request.setAttribute("isS", isS);

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"container\">\n");
      out.write("    <!-- 		<img src=\"images/beach.jpg\" class=\"img-fluid \" alt=\"Responsive image\"> -->\n");
      out.write("    <div class=\"row justify-content-center\">\n");
      out.write("        <div class=\"col-md-12\">\n");
      out.write("            <br>\n");
      out.write("            <div class=\"card\">\n");
      out.write("                <div class=\"card-header\">\n");
      out.write("                    <h4>");
      out.print(dto.getTitle());
      out.write("\n");
      out.write("                    </h4>\n");
      out.write("                    <div class=\"small text-muted\">\n");
      out.write("                        작성자: ");
      out.print(dto.getId());
      out.write(",\n");
      out.write("                        작성일: ");
      out.print(dto.getWdate());
      out.write(",\n");
      out.write("                        조회수: ");
      out.print(dto.getReadcount());
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"card-body\">\n");
      out.write("                    ");

                        for (int i = 1; i <= 11; i++) {
                            if (dto.getSeq() == i) {
                    
      out.write("\n");
      out.write("                    <img src=\"images/review/");
      out.print(i);
      out.write(".jpg\" class=\"d-block w-100\">\n");
      out.write("                    ");

                            }
                        }
                    
      out.write("\n");
      out.write("                    ");
      out.print(dto.getContent());
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <br>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"row justify-content-center\">\n");
      out.write("        <div class=\"col-md-12\">\n");
      out.write("            <!-- 수정, 삭제는 로그인한 본인한테만 보이게 -->\n");
      out.write("            ");

                if (dto.getId().equals(login.getId())) {
            
      out.write("\n");
      out.write("            <div class=\"d-flex justify-content-end\">\n");
      out.write("                <button type=\"submit\" class=\"btn btn-secondary mr-3\"\n");
      out.write("                        onclick=\"reviewUpdate(");
      out.print(dto.getSeq());
      out.write(")\">수정\n");
      out.write("                </button>\n");
      out.write("                <button type=\"submit\" class=\"btn btn-secondary\"\n");
      out.write("                        onclick=\"reviewDelete(");
      out.print(dto.getSeq());
      out.write(")\">삭제\n");
      out.write("                </button>\n");
      out.write("                ");

                    }
                
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <br>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"container\">\n");
      out.write("    <div class=\"row justify-content-center\">\n");
      out.write("        <div class=\"col-md-12\">\n");
      out.write("            <form action=\"reviewCommentWrite.do\" method=\"get\">\n");
      out.write("                <!-- 	<input type=\"hidden\" name=\"board_id\" value=\"글번호\"> -->\n");
      out.write("                <input type=\"hidden\" name=\"seq\" value=\"");
      out.print(dto.getSeq());
      out.write("\">\n");
      out.write("                <input type=\"hidden\" name=\"id\" value=\"");
      out.print(login.getId());
      out.write("\">\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("						<textarea class=\"form-control\" id=\"comment_content\" name=\"content\"\n");
      out.write("                                  rows=\"3\"></textarea>\n");
      out.write("                </div>\n");
      out.write("                <button type=\"submit\" class=\"btn btn-secondary\">댓글 등록</button>\n");
      out.write("            </form>\n");
      out.write("            <br>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"row justify-content-center\">\n");
      out.write("        <div class=\"col-md-12\">\n");
      out.write("            <div id=\"li\">\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("    function reviewUpdate(seq) {\n");
      out.write("        location.href = \"reviewUpdate.do?seq=\" + seq;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function reviewDelete(seq) {\n");
      out.write("        location.href = \"reviewDelete.do?seq=\" + seq;  // update del=1\n");
      out.write("    }\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("    $(document).ready(function () {\n");
      out.write("        $.ajax({\n");
      out.write("            url: \"reviewCommentList.do\",\n");
      out.write("            type: \"get\",\n");
      out.write("            data: {\"seq\":");
      out.print(dto.getSeq() );
      out.write("},\n");
      out.write("            success: function (list) {\n");
      out.write("                // alert('success');\n");
      out.write("                // alert(JSON.stringify(list));\n");
      out.write("\n");
      out.write("                $(\"#li\").html(\"\");\n");
      out.write("\n");
      out.write("                $.each(list, function (index, item) {\n");
      out.write("                    let str = \"<div class='card mt-1'>\"\n");
      out.write("                        + 			\"<div class='card-header'>\" + item.id + \"</div>\"\n");
      out.write("                        + 			\"<div class='card-body'>\"\n");
      out.write("                        + 				\"<ul class='list-unstyled'>\"\n");
      out.write("                        + 					\"<li>\"\n");
      out.write("                        + 					\"<div>\" + item.content + \"</div>\"\n");
      out.write("                        + 					\"<br>\"\n");
      out.write("                        + 					\"<div>작성일: \" + item.wdate + \"</div>\"\n");
      out.write("                        + 					\"</li>\"\n");
      out.write("                        + 				\"</ul>\"\n");
      out.write("                        + 			\"</div>\"\n");
      out.write("                        + 	\"</div>\"\n");
      out.write("                        + 	\"<br>\"\n");
      out.write("                    $(\"#li\").append(str);\n");
      out.write("\n");
      out.write("                });\n");
      out.write("            },\n");
      out.write("            error: function () {\n");
      out.write("                alert('error');\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
