/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-03-26 06:17:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.loginScreen;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class regi_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("	<meta charset=\"UTF-8\">\n");
      out.write("	<title>Insert title here</title>\n");
      out.write("	 <link rel=\"stylesheet\" href=\"css/login.css\">\n");
      out.write("    <script src=\"https://kit.fontawesome.com/51db22a717.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900\" rel=\"stylesheet\">\n");
      out.write("    <!-- BootStrap -->\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js\"></script>	<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.0.8/css/all.css\">\n");
      out.write("	\n");
      out.write("	<style type=\"text/css\">\n");
      out.write("		header h1 {\n");
      out.write("		    font-size: 50px;\n");
      out.write("		    color:\n");
      out.write("		}\n");
      out.write("		body{\n");
      out.write("			/* background:var(--body-background-color); */\n");
      out.write("			/* 배경 꽉차게 */\n");
      out.write("			background: linear-gradient(rgba(0, 0, 0, 0.3),rgba(0, 0, 0, 0.3)),\n");
      out.write("							url('./pageimage/image01.jpg')\n");
      out.write("							no-repeat center fixed;\n");
      out.write("			-webkit-background-size: cover;\n");
      out.write("			-moz-background-size: cover;\n");
      out.write("			-o-background-size: cover;\n");
      out.write("			background-size: cover;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		a {\n");
      out.write("			text-decoration: none;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		a:hover {\n");
      out.write("			text-decoration: underline;\n");
      out.write("			color:#666;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		.login-button-wrap:hover {\n");
      out.write("			--green-color:#666;\n");
      out.write("			--green-border-color: #666;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.blog-header-logo {\n");
      out.write("		    font-family: \"Playfair Display\", Georgia, \"Times New Roman\", serif;\n");
      out.write("		    font-size: 3.5rem;\n");
      out.write("		    color: white;\n");
      out.write("		    text-shadow: 0 2px 20px rgba(0,0,0,0);\n");
      out.write("		}b \n");
      out.write("	</style>\n");
      out.write("	</head>\n");
      out.write("	<body>\n");
      out.write("	\n");
      out.write("	<div class=\"main-container\" id=\"container\">\n");
      out.write("		<header class=\"blog-header py-3\" style=\"margin-top: -8%;\">\n");
      out.write("	         <div class=\"col-4 text-center\">\n");
      out.write("	                <a class=\"blog-header-logo\" href=\"maintraballoon.do\">Traballoon</a>\n");
      out.write("	         </div>\n");
      out.write("	    </header>\n");
      out.write("	\n");
      out.write("\n");
      out.write("		<h4 style=\"color:white\">회원가입</h4>\n");
      out.write("		\n");
      out.write("		<form action=\"regiAf.do\" method=\"post\" class=\"login-input-section-wrap\" style=\"margin-top: 0%;\">\n");
      out.write("			<!-- id -->\n");
      out.write("			<div class=\"input-group mb-3\">\n");
      out.write("				<span class=\"input-group-text\" id=\"basic-addon1\">\n");
      out.write("					<i class=\"fa fa-user\" aria-hidden=\"true\"></i>\n");
      out.write("				</span>\n");
      out.write("			    <input id=\"id\" name=\"id\" placeholder=\" id\" type=\"text\" class=\"form-control\">\n");
      out.write("\n");
      out.write("			    <!-- idcheck -->\n");
      out.write("		    	<input type=\"button\" class=\"btn btn-danger\" value=\"중복확인\" id=\"idChkBtn\" />\n");
      out.write("		    </div>\n");
      out.write("		\n");
      out.write("		    <div style=\"float:left;\">\n");
      out.write("		   		<p id=\"idcheck\" style=\"margin-left:-60%;\"></p>\n");
      out.write("		    </div>\n");
      out.write("		    	\n");
      out.write("		    <!-- Fullname -->\n");
      out.write("			<div class=\"input-group mb-3\">\n");
      out.write("				<span class=\"input-group-text\" id=\"basic-addon1\">\n");
      out.write("					<i class=\"fa fa-user\" aria-hidden=\"true\"></i>\n");
      out.write("				</span>\n");
      out.write("		        <input name=\"name\" placeholder=\"Full name\" type=\"text\" class=\"form-control\">\n");
      out.write("		    </div>\n");
      out.write("		    \n");
      out.write("		    <!-- nickname -->\n");
      out.write("		    <div class=\"input-group mb-3\">\n");
      out.write("				<span class=\"input-group-text\" id=\"basic-addon1\">\n");
      out.write("					<i class=\"fa fa-user\" aria-hidden=\"true\"></i>\n");
      out.write("				</span>\n");
      out.write("		        <input name=\"nickname\" class=\"form-control\" placeholder=\"NickName\" type=\"text\">\n");
      out.write("		    </div>\n");
      out.write("		    \n");
      out.write("		    <!-- 주소 -->\n");
      out.write("		  	 <div class=\"input-group mb-3\">\n");
      out.write("				<span class=\"input-group-text\" id=\"basic-addon1\">\n");
      out.write("				   	<i class=\"fa fa-map-marker\" aria-hidden=\"true\"></i>\n");
      out.write("				</span>\n");
      out.write("		        <input name=\"address\" class=\"form-control\" placeholder=\"address\" type=\"text\">\n");
      out.write("		    </div>\n");
      out.write("		    \n");
      out.write("		    <!-- 이메일 -->\n");
      out.write("		    <div class=\"input-group mb-3\">\n");
      out.write("				<span class=\"input-group-text\" id=\"basic-addon1\">\n");
      out.write("				   	<i  class=\"fa fa-envelope\" aria-hidden=\"true\"></i>\n");
      out.write("				</span>\n");
      out.write("		        <input name=\"email\" class=\"form-control\" placeholder=\"Email address\" type=\"email\">\n");
      out.write("		    </div>\n");
      out.write("		    \n");
      out.write("\n");
      out.write("		    <!-- 전화번호\n");
      out.write("		    <div>\n");
      out.write("		    	<div class=\"input-group mb-3\">\n");
      out.write("				    <span class=\"input-group-text\" id=\"basic-addon1\">\n");
      out.write("				    	<i class=\"fa fa-phone\" aria-hidden=\"true\"></i>\n");
      out.write("				    </span>\n");
      out.write("					<select class=\"custom-select\" style=\"max-width: 120px;\">\n");
      out.write("					    <option selected=\"selected\">+02</option>\n");
      out.write("					    <option value=\"1\">+032</option>\n");
      out.write("					    <option value=\"2\">+041</option>\n");
      out.write("					    <option value=\"3\">+053</option>\n");
      out.write("					    <option value=\"4\">+010</option>\n");
      out.write("					</select>\n");
      out.write("			    	<input name=\"phonenumber\" placeholder=\"Phone number\" class=\"form-control\" type=\"text\">\n");
      out.write("				</div>\n");
      out.write("		    </div> \n");
      out.write("		    -->\n");
      out.write("		    \n");
      out.write("		    <!-- 전화번호 -->\n");
      out.write("		    <div class=\"input-group mb-3\">\n");
      out.write("				<span class=\"input-group-text\" id=\"basic-addon1\">\n");
      out.write("					<i class=\"fa fa-mobile\" aria-hidden=\"true\"></i>\n");
      out.write("				</span>\n");
      out.write("				 <select class=\"form-select\" style=\"padding-right: \" id=\"inputGroupSelect01\">\n");
      out.write("					<option selected=\"selected\">+02</option>\n");
      out.write("					<option value=\"1\">+032</option>\n");
      out.write("					<option value=\"2\">+041</option>\n");
      out.write("					<option value=\"3\">+053</option>\n");
      out.write("					<option value=\"4\">+010</option>\n");
      out.write("			  	</select>\n");
      out.write("			    <input name=\"phonenumber\" placeholder=\"Phone number\" class=\"form-control\" type=\"text\" aria-label=\"Text input with dropdown button\">\n");
      out.write("		    </div>\n");
      out.write("		    \n");
      out.write("		    \n");
      out.write("		    <!-- 직업 -->\n");
      out.write("		   <div class=\"input-group mb-3\">\n");
      out.write("				<span class=\"input-group-text\" id=\"basic-addon1\">\n");
      out.write("					<i class=\"fa fa-building\" aria-hidden=\"true\"></i>\n");
      out.write("				</span>\n");
      out.write("			  <select class=\"form-select\" id=\"inputGroupSelect01\">\n");
      out.write("				<option selected=\"selected\">직업</option>\n");
      out.write("				<option>디자이너</option>\n");
      out.write("				<option>프로그래머</option>\n");
      out.write("				<option>자영업</option>\n");
      out.write("			  </select>\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("			<!-- password -->\n");
      out.write("		    <div class=\"input-group mb-3\">\n");
      out.write("				<span class=\"input-group-text\" id=\"basic-addon1\">\n");
      out.write("					<i class=\"fa fa-lock\" aria-hidden=\"true\"></i>\n");
      out.write("				</span>\n");
      out.write("		        <input id=\"\" name=\"pwd\" placeholder=\"Create password\" type=\"password\" class=\"form-control\">\n");
      out.write("		    </div>\n");
      out.write("		    \n");
      out.write("			<!-- repeat password -->\n");
      out.write("		    <div class=\"input-group mb-3\">\n");
      out.write("				<span class=\"input-group-text\" id=\"basic-addon1\">\n");
      out.write("					<i class=\"fa fa-lock\" aria-hidden=\"true\"></i>\n");
      out.write("				</span>\n");
      out.write("		        <input placeholder=\"Repeat password\" type=\"password\" class=\"form-control\">\n");
      out.write("		    </div>\n");
      out.write("		    \n");
      out.write("		    <!-- Create Account -->        \n");
      out.write("		    <div class=\"login-button-wrap\">\n");
      out.write("		        <button type=\"submit\"> Create Account  </button>\n");
      out.write("		    </div>\n");
      out.write("		</form>\n");
      out.write("		\n");
      out.write("		<section class=\"Easy-sgin-in-wrap\">\n");
      out.write("	        <a href=\"login.do\" class=\"forget-msg\">Have an account?  Log In</a>\n");
      out.write("	    </section>\n");
      out.write("	    \n");
      out.write("		 <footer style=\"margin-bottom: 5%;\">\n");
      out.write("	        <div class=\"copyright-wrap\">\n");
      out.write("	            <span>Thank you for visiting Multicampus Team Four's website!</span>\n");
      out.write("	        	<br>\n");
      out.write("	        	<p style=\"font-size: 12px;\">Designed and developed by | 권하나, 김동민, 김영권, 백다연, 심재훈 | © 2023 All Rights Reserved</p>\n");
      out.write("	        </div>\n");
      out.write("	    </footer>\n");
      out.write("	</div>\n");
      out.write("	  \n");
      out.write("	\n");
      out.write("	<script type=\"text/javascript\">\n");
      out.write("	$(document).ready(function() {\n");
      out.write("		\n");
      out.write("		$(\"#idChkBtn\").click(function() {		\n");
      out.write("			// id의 빈칸을 조사!\n");
      out.write("			\n");
      out.write("			$.ajax({\n");
      out.write("				type:\"post\",\n");
      out.write("				url:\"idcheck.do\",\n");
      out.write("				data:{ \"id\":$(\"#id\").val() },\n");
      out.write("				success:function(msg){\n");
      out.write("					if(msg == \"YES\"){\n");
      out.write("						$(\"#idcheck\").css(\"color\", \"#ffffff\");\n");
      out.write("						$(\"#idcheck\").text(\"사용할 수 있는 아이디입니다\");\n");
      out.write("					}else{\n");
      out.write("						$(\"#idcheck\").css(\"color\", \"#ff0000\");\n");
      out.write("						$(\"#idcheck\").text(\"사용중인 아이디입니다\");\n");
      out.write("						$(\"#id\").val(\"\");\n");
      out.write("					}\n");
      out.write("				},\n");
      out.write("				error:function(){\n");
      out.write("					alert('error');\n");
      out.write("				}\n");
      out.write("			});\n");
      out.write("		});\n");
      out.write("	});\n");
      out.write("	</script>\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
